name: "Deploy Action"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

     
     
      
      - name: Cat for GitHub Actions
        id: get_key
        run: |
          echo "keybase64=$(cat ${{ github.workspace }}/__tests__/test_key_b64.txt)" >> $GITHUB_ENV

      - uses: ./
        name: Sign APK
        with:
          releaseDirectory: __tests__/apk
          signingKeyBase64: ${{ env.keybase64 }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

      - uses: ./
        name: Sign AAB
        with:
          releaseDirectory: __tests__/aab
          signingKeyBase64: ${{ env.keybase64 }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

  release:
    needs: test
    runs-on: ubuntu-latest
    name: Update action

    steps:
      - uses: actions/checkout@v3
        name: Checkout code
